spring:
  thymeleaf:
    prefix:
      - classpath:/static
      - classpath:/templates
      - classpath:/templates/thymeleaf/

    suffix: .html
    mode: HTML
    cache: false
    check-template-location: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Seoul
    username: root
    password: dltmdgjs0927

  jpa:
    open-in-view: false

    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

#naver:
#  client:
#    id: ${NAVER_CLIENT_ID}
#    secret: ${NAVER_CLIENT_SECRET}
#    url: ${NAVER_REDIRECT_URL}